/*
 * Created on 8 Nov 2016 ( Time 18:01:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.hisd.domestic.model;

import java.io.Serializable;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name="tbl_userlogin")

public class TblUserLogin implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long       userId           ;
    private int isCTPLUser=0;
    private int    failedattempt ;
    private String     loginid      ;
    private String     password     ;
    private Integer    cstatus       ;
    private TblDesignation tblDesignation;
    private String forgotpwdHash;
    private Date forgotpwdExpiryDate;
    private Date lastLogin;
    private int isFirstLogin;
    private TblUserType tblUserType;
    private TblCaseType tblCaseType;
    private String otherdesignation;


    @Column(name="isFirstLogin")
    public int getIsFirstLogin() {
		return isFirstLogin;
	}

	public void setIsFirstLogin(int isFirstLogin) {
		this.isFirstLogin = isFirstLogin;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="lastLogin")
	public Date getLastLogin() {
		return lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name="isCTPLUser")
    public int getIsCTPLUser() {
		return isCTPLUser;
	}

	public void setIsCTPLUser(int isCTPLUser) {
		this.isCTPLUser = isCTPLUser;
	}

	@OneToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="designationId")
    public TblDesignation getTblDesignation() {
		return tblDesignation;
	}

	public void setTblDesignation(TblDesignation tblDesignation) {
		this.tblDesignation = tblDesignation;
	}

	/*public TblUserLogin(int i) {
    	this.userId = (long) i ;
    }*/
	public TblUserLogin(long i) {
    	this.userId =  i ;
    }
    public TblUserLogin() {
    }
    
    public void setUserId( Long userId ) {
        this.userId = userId ;
    }
    @Id
    @GeneratedValue
    @Column(name="userId")
    public Long getUserId() {
        return this.userId;
    }

    public void setFailedattempt( int failedattempt ) {
        this.failedattempt = failedattempt;
    }
    @Column(name="failedattempt")
    public int getFailedattempt() {
        return this.failedattempt;
    }

    public void setLoginid( String loginid ) {
        this.loginid = loginid;
    }
    @Column(name="loginid")
    public String getLoginid() {
        return this.loginid;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    @Column(name="password", length=255)
    public String getPassword() {
        return this.password;
    }

    
    @Column(name="cstatus")
	public Integer getCstatus() {
		return cstatus;
	}

	public void setCstatus(Integer cstatus) {
		this.cstatus = cstatus;
	}
	@OneToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="casetypeid")
    public TblCaseType getTblCaseType() {
		return tblCaseType;
	}

	public void setTblCaseType(TblCaseType tblCaseType) {
		this.tblCaseType = tblCaseType;
	}
	
	
	@OneToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usertypeid")
    public TblUserType getTblUserType() {
		return tblUserType;
	}

	public void setTblUserType(TblUserType tblUserType) {
		this.tblUserType = tblUserType;
	}
	
	@Column(name="forgotpwdHash")
	public String getForgotpwdHash() {
		return forgotpwdHash;
	}

	public void setForgotpwdHash(String forgotpwdHash) {
		this.forgotpwdHash = forgotpwdHash;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="forgotpwdExpiryDate")
	public Date getForgotpwdExpiryDate() {
		return forgotpwdExpiryDate;
	}
	
	@Column(name="otherdesignation")
	 public String getOtherdesignation() {
		return otherdesignation;
	}

	public void setOtherdesignation(String otherdesignation) {
		this.otherdesignation = otherdesignation;
	}
	

	public void setForgotpwdExpiryDate(Date forgotpwdExpiryDate) {
		this.forgotpwdExpiryDate = forgotpwdExpiryDate;
	}

   

	public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(userId);
        sb.append("]:"); 
        sb.append(failedattempt);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(cstatus);
        return sb.toString(); 
    }

}
