/*
 * Created on 22 Nov 2016 ( Time 07:58:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.hisd.common.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "tbl_link"
 *
 *
 */

@Entity
@Table(name="tbl_mailmessage")
public class TblMailMessage implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer    mailmessageid       ;
    private String     mailTo     ;
    private String     mailFrom       ;
    private String     mailSubject         ;
    private String     mailBody  ;
    private Integer mailSent;
    private String mailDescription;
    
    
    
    @Column(name="mailDescription", nullable=false)
    public String getMailDescription() {
		return mailDescription;
	}
	public void setMailDescription(String mailDescription) {
		this.mailDescription = mailDescription;
	}
	@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="mailmessageid", nullable=false)
	public Integer getMailmessageid() {
		return mailmessageid;
	}
	public void setMailmessageid(Integer mailmessageid) {
		this.mailmessageid = mailmessageid;
	}
	
	@Column(name="mailTo", nullable=false)
	public String getMailTo() {
		return mailTo;
	}
	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}
	
	@Column(name="mailFrom", nullable=false,length=50)
	public String getMailFrom() {
		return mailFrom;
	}
	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}
	
	@Column(name="mailSubject", nullable=false)
	public String getMailSubject() {
		return mailSubject;
	}
	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}
	
	@Column(name="mailBody", nullable=false)
	public String getMailBody() {
		return mailBody;
	}
	public void setMailBody(String mailBody) {
		this.mailBody = mailBody;
	}
	
	@Column(name="mailSent", nullable=false)
	public Integer getMailSent() {
		return mailSent;
	}
	public void setMailSent(Integer mailSent) {
		this.mailSent = mailSent;
	}
	
	@Override
	public String toString() {
		return "TblMailMessage [mailmessageid=" + mailmessageid + ", mailTo="
				+ mailTo + ", mailFrom=" + mailFrom + ", mailSubject="
				+ mailSubject + ", mailBody=" + mailBody + ", mailSent="
				+ mailSent + ", mailDescription=" + mailDescription + "]";
	}
	public TblMailMessage() {
		super();
	}

    

}
